CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  jid VARCHAR(255) NOT NULL UNIQUE,
  domain VARCHAR(255) NOT NULL,
  email_id VARCHAR(255) UNIQUE NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- modified column definition
  last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT true,
  mobile_no VARCHAR(20) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  avatar_url VARCHAR(2048) NULL,
  PRIMARY KEY (id)
);

CREATE TABLE files (
  id CHAR(36) PRIMARY KEY NOT NULL,
  from_ VARCHAR(255) NOT NULL,
  to_ VARCHAR(255) NOT NULL,
  domain VARCHAR(255) NOT NULL,
  type VARCHAR(10) NOT NULL,
  url VARCHAR(2048) NOT NULL,
  message_id VARCHAR(72) NOT NULL,
  ext VARCHAR(10) NOT NULL,
  uploaded_at DATETIME
);

